DROP DATABASE IF EXISTS SALES_4_US;
CREATE DATABASE SALES_4_US;
USE SALES_4_US;

CREATE TABLE USER (
ID INT NOT NULL auto_increment PRIMARY KEY,
NAME VARCHAR (20) NOT NULL,
PASSWORD VARCHAR (200) NOT NULL,
EMAIL VARCHAR (20) NOT NULL
);

CREATE TABLE PURCHASE (
ID INT NOT NULL auto_increment PRIMARY KEY,
DATE DATETIME NOT NULL,
TOTAL_PRIZE DECIMAL NOT NULL,
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE PROVIDER (
ID INT NOT NULL auto_increment PRIMARY KEY,
NAME VARCHAR (40) NOT NULL,
DIRECTION VARCHAR (120) NOT NULL,
PHONE INT NOT NULL,
WEBSITE VARCHAR (40) NOT NULL,
EMAIL VARCHAR (40) NOT NULL
);

CREATE TABLE PRODUCT(
ID INT NOT NULL auto_increment PRIMARY KEY,
PROVIDER_ID INT NOT NULL, 
NAME VARCHAR (20) NOT NULL,
PRIZE DECIMAL NOT NULL,
CATEGORY VARCHAR (40) NOT NULL,
DESCRIPTION VARCHAR (500) NOT NULL
);

CREATE TABLE LINIA_PURCHASE (
PURCHASE_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
UNIT INT NOT NULL,
PRIMARY KEY (PURCHASE_ID, PRODUCT_ID),
FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE (ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE OPINION (
ID INT NOT NULL auto_increment PRIMARY KEY,
USER_ID INT NOT NULL,
TITLE VARCHAR (40) NOT NULL,
DESCRIPTION VARCHAR (400) NOT NULL,
STARS INT,
PRODUCT_ID INT NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE ROLE (
id INT NOT NULL auto_increment,
name ENUM ('admin', 'client'),
userid INT NOT Null,
primary key (id),
INDEX fkRolUsuari_idx (userId ASC) VISIBLE,
CONSTRAINT fkRolUsuer
Foreign key (userid)
REFERENCES SALES_4_US.USER (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);


INSERT INTO USER(name, password, email) VALUES ("jose", "$2a$10$N2Gyo4ryYoCZNS3im0Q/uO1N2FpXDiTsYaF72e/T1RUmnNwbG08hW", "jose@jose.local");
Select * FROM USER;
INSERT INTO ROLE(name, userid) VALUES ('admin', 1);