DROP DATABASE IF EXISTS SALES_4_US;
CREATE DATABASE SALES_4_US;
USE SALES_4_US;

CREATE TABLE user (
user_id INT NOT NULL auto_increment PRIMARY KEY,
user_name VARCHAR (20) NOT NULL,
password VARCHAR (200) NOT NULL,
email VARCHAR (20) NOT NULL
);

CREATE TABLE PURCHASE (
ID INT NOT NULL auto_increment PRIMARY KEY,
DATE DATETIME NOT NULL,
TOTAL_PRIZE DECIMAL NOT NULL,
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES user(user_id)
);

CREATE TABLE PROVIDER (
ID INT NOT NULL auto_increment PRIMARY KEY,
NAME VARCHAR (40) NOT NULL,
DIRECTION VARCHAR (120) NOT NULL,
PHONE INT NOT NULL,
WEBSITE VARCHAR (40) NOT NULL,
EMAIL VARCHAR (40) NOT NULL
);

CREATE TABLE PRODUCT(
ID INT NOT NULL auto_increment PRIMARY KEY,
PROVIDER_ID INT NOT NULL, 
NAME VARCHAR (20) NOT NULL,
PRIZE DECIMAL NOT NULL,
CATEGORY VARCHAR (40) NOT NULL,
DESCRIPTION VARCHAR (500) NOT NULL
);

CREATE TABLE LINIA_PURCHASE (
PURCHASE_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
UNIT INT NOT NULL,
PRIMARY KEY (PURCHASE_ID, PRODUCT_ID),
FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE (ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE OPINION (
ID INT NOT NULL auto_increment PRIMARY KEY,
USER_ID INT NOT NULL,
TITLE VARCHAR (40) NOT NULL,
DESCRIPTION VARCHAR (400) NOT NULL,
STARS INT,
PRODUCT_ID INT NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
FOREIGN KEY (USER_ID) REFERENCES user (user_id)
);


CREATE TABLE rol (
  `id_rol` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  PRIMARY KEY (`id_rol`),
  KEY `fkRolUsuari_idx` (`user_id`),
  CONSTRAINT `fkRolUsuari` FOREIGN KEY (`user_id`) REFERENCES user (`user_id`)
);



INSERT INTO user(user_name, password, email) VALUES ("jose", "$2a$10$N2Gyo4ryYoCZNS3im0Q/uO1N2FpXDiTsYaF72e/T1RUmnNwbG08hW", "jose@jose.local");
Select * FROM user;
INSERT INTO rol(name, user_id) VALUES ('admin', 1);